### ISSUE TITLE
Not working on Woocommerce 2.3.11

### ISSUE THREAD

**Issue by warisaajkal** [qcloud/WooCommerce-Tabbed-Category-Wise-Product-Listing#1]
This plugin not working on woocommerce 2.3.11 and wordpress version 4.2.2 I have added the short code [product-cat].

**Comment by darmar** [comment]
Same  with WooCommerce 2.5.3

**Comment by Shibly** [comment]
It has been fixed. Checked with latest version of woo-commerce.
